/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PinRouteImport } from './routes/pin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRegistroRouteImport } from './routes/_app.registro'
import { Route as AppInicioRouteImport } from './routes/_app.inicio'
import { Route as AppAjustesRouteImport } from './routes/_app.ajustes'
import { Route as AppDeudoresIndexRouteImport } from './routes/_app.deudores.index'
import { Route as AppAjustesIndexRouteImport } from './routes/_app.ajustes.index'
import { Route as AppDeudoresClienteIdRouteImport } from './routes/_app.deudores.$clienteId'
import { Route as AppAjustesHistorialRouteImport } from './routes/_app.ajustes.historial'
import { Route as AppAjustesEmpleadosRouteImport } from './routes/_app.ajustes.empleados'
import { Route as AppAjustesCategoriasRouteImport } from './routes/_app.ajustes.categorias'
import { Route as AppAjustesCatalogoRouteImport } from './routes/_app.ajustes.catalogo'
import { Route as AppAjustesArqueoRouteImport } from './routes/_app.ajustes.arqueo'

const PinRoute = PinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRegistroRoute = AppRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => AppRoute,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRoute,
} as any)
const AppAjustesRoute = AppAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AppRoute,
} as any)
const AppDeudoresIndexRoute = AppDeudoresIndexRouteImport.update({
  id: '/deudores/',
  path: '/deudores/',
  getParentRoute: () => AppRoute,
} as any)
const AppAjustesIndexRoute = AppAjustesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAjustesRoute,
} as any)
const AppDeudoresClienteIdRoute = AppDeudoresClienteIdRouteImport.update({
  id: '/deudores/$clienteId',
  path: '/deudores/$clienteId',
  getParentRoute: () => AppRoute,
} as any)
const AppAjustesHistorialRoute = AppAjustesHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AppAjustesRoute,
} as any)
const AppAjustesEmpleadosRoute = AppAjustesEmpleadosRouteImport.update({
  id: '/empleados',
  path: '/empleados',
  getParentRoute: () => AppAjustesRoute,
} as any)
const AppAjustesCategoriasRoute = AppAjustesCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppAjustesRoute,
} as any)
const AppAjustesCatalogoRoute = AppAjustesCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AppAjustesRoute,
} as any)
const AppAjustesArqueoRoute = AppAjustesArqueoRouteImport.update({
  id: '/arqueo',
  path: '/arqueo',
  getParentRoute: () => AppAjustesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pin': typeof PinRoute
  '/ajustes': typeof AppAjustesRouteWithChildren
  '/inicio': typeof AppInicioRoute
  '/registro': typeof AppRegistroRoute
  '/ajustes/arqueo': typeof AppAjustesArqueoRoute
  '/ajustes/catalogo': typeof AppAjustesCatalogoRoute
  '/ajustes/categorias': typeof AppAjustesCategoriasRoute
  '/ajustes/empleados': typeof AppAjustesEmpleadosRoute
  '/ajustes/historial': typeof AppAjustesHistorialRoute
  '/deudores/$clienteId': typeof AppDeudoresClienteIdRoute
  '/ajustes/': typeof AppAjustesIndexRoute
  '/deudores/': typeof AppDeudoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pin': typeof PinRoute
  '/inicio': typeof AppInicioRoute
  '/registro': typeof AppRegistroRoute
  '/ajustes/arqueo': typeof AppAjustesArqueoRoute
  '/ajustes/catalogo': typeof AppAjustesCatalogoRoute
  '/ajustes/categorias': typeof AppAjustesCategoriasRoute
  '/ajustes/empleados': typeof AppAjustesEmpleadosRoute
  '/ajustes/historial': typeof AppAjustesHistorialRoute
  '/deudores/$clienteId': typeof AppDeudoresClienteIdRoute
  '/ajustes': typeof AppAjustesIndexRoute
  '/deudores': typeof AppDeudoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pin': typeof PinRoute
  '/_app/ajustes': typeof AppAjustesRouteWithChildren
  '/_app/inicio': typeof AppInicioRoute
  '/_app/registro': typeof AppRegistroRoute
  '/_app/ajustes/arqueo': typeof AppAjustesArqueoRoute
  '/_app/ajustes/catalogo': typeof AppAjustesCatalogoRoute
  '/_app/ajustes/categorias': typeof AppAjustesCategoriasRoute
  '/_app/ajustes/empleados': typeof AppAjustesEmpleadosRoute
  '/_app/ajustes/historial': typeof AppAjustesHistorialRoute
  '/_app/deudores/$clienteId': typeof AppDeudoresClienteIdRoute
  '/_app/ajustes/': typeof AppAjustesIndexRoute
  '/_app/deudores/': typeof AppDeudoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pin'
    | '/ajustes'
    | '/inicio'
    | '/registro'
    | '/ajustes/arqueo'
    | '/ajustes/catalogo'
    | '/ajustes/categorias'
    | '/ajustes/empleados'
    | '/ajustes/historial'
    | '/deudores/$clienteId'
    | '/ajustes/'
    | '/deudores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pin'
    | '/inicio'
    | '/registro'
    | '/ajustes/arqueo'
    | '/ajustes/catalogo'
    | '/ajustes/categorias'
    | '/ajustes/empleados'
    | '/ajustes/historial'
    | '/deudores/$clienteId'
    | '/ajustes'
    | '/deudores'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/pin'
    | '/_app/ajustes'
    | '/_app/inicio'
    | '/_app/registro'
    | '/_app/ajustes/arqueo'
    | '/_app/ajustes/catalogo'
    | '/_app/ajustes/categorias'
    | '/_app/ajustes/empleados'
    | '/_app/ajustes/historial'
    | '/_app/deudores/$clienteId'
    | '/_app/ajustes/'
    | '/_app/deudores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PinRoute: typeof PinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pin': {
      id: '/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/registro': {
      id: '/_app/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof AppRegistroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inicio': {
      id: '/_app/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ajustes': {
      id: '/_app/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AppAjustesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deudores/': {
      id: '/_app/deudores/'
      path: '/deudores'
      fullPath: '/deudores/'
      preLoaderRoute: typeof AppDeudoresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ajustes/': {
      id: '/_app/ajustes/'
      path: '/'
      fullPath: '/ajustes/'
      preLoaderRoute: typeof AppAjustesIndexRouteImport
      parentRoute: typeof AppAjustesRoute
    }
    '/_app/deudores/$clienteId': {
      id: '/_app/deudores/$clienteId'
      path: '/deudores/$clienteId'
      fullPath: '/deudores/$clienteId'
      preLoaderRoute: typeof AppDeudoresClienteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ajustes/historial': {
      id: '/_app/ajustes/historial'
      path: '/historial'
      fullPath: '/ajustes/historial'
      preLoaderRoute: typeof AppAjustesHistorialRouteImport
      parentRoute: typeof AppAjustesRoute
    }
    '/_app/ajustes/empleados': {
      id: '/_app/ajustes/empleados'
      path: '/empleados'
      fullPath: '/ajustes/empleados'
      preLoaderRoute: typeof AppAjustesEmpleadosRouteImport
      parentRoute: typeof AppAjustesRoute
    }
    '/_app/ajustes/categorias': {
      id: '/_app/ajustes/categorias'
      path: '/categorias'
      fullPath: '/ajustes/categorias'
      preLoaderRoute: typeof AppAjustesCategoriasRouteImport
      parentRoute: typeof AppAjustesRoute
    }
    '/_app/ajustes/catalogo': {
      id: '/_app/ajustes/catalogo'
      path: '/catalogo'
      fullPath: '/ajustes/catalogo'
      preLoaderRoute: typeof AppAjustesCatalogoRouteImport
      parentRoute: typeof AppAjustesRoute
    }
    '/_app/ajustes/arqueo': {
      id: '/_app/ajustes/arqueo'
      path: '/arqueo'
      fullPath: '/ajustes/arqueo'
      preLoaderRoute: typeof AppAjustesArqueoRouteImport
      parentRoute: typeof AppAjustesRoute
    }
  }
}

interface AppAjustesRouteChildren {
  AppAjustesArqueoRoute: typeof AppAjustesArqueoRoute
  AppAjustesCatalogoRoute: typeof AppAjustesCatalogoRoute
  AppAjustesCategoriasRoute: typeof AppAjustesCategoriasRoute
  AppAjustesEmpleadosRoute: typeof AppAjustesEmpleadosRoute
  AppAjustesHistorialRoute: typeof AppAjustesHistorialRoute
  AppAjustesIndexRoute: typeof AppAjustesIndexRoute
}

const AppAjustesRouteChildren: AppAjustesRouteChildren = {
  AppAjustesArqueoRoute: AppAjustesArqueoRoute,
  AppAjustesCatalogoRoute: AppAjustesCatalogoRoute,
  AppAjustesCategoriasRoute: AppAjustesCategoriasRoute,
  AppAjustesEmpleadosRoute: AppAjustesEmpleadosRoute,
  AppAjustesHistorialRoute: AppAjustesHistorialRoute,
  AppAjustesIndexRoute: AppAjustesIndexRoute,
}

const AppAjustesRouteWithChildren = AppAjustesRoute._addFileChildren(
  AppAjustesRouteChildren,
)

interface AppRouteChildren {
  AppAjustesRoute: typeof AppAjustesRouteWithChildren
  AppInicioRoute: typeof AppInicioRoute
  AppRegistroRoute: typeof AppRegistroRoute
  AppDeudoresClienteIdRoute: typeof AppDeudoresClienteIdRoute
  AppDeudoresIndexRoute: typeof AppDeudoresIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAjustesRoute: AppAjustesRouteWithChildren,
  AppInicioRoute: AppInicioRoute,
  AppRegistroRoute: AppRegistroRoute,
  AppDeudoresClienteIdRoute: AppDeudoresClienteIdRoute,
  AppDeudoresIndexRoute: AppDeudoresIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PinRoute: PinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
