/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PinRouteImport } from './routes/pin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRegistroRouteImport } from './routes/_app.registro'
import { Route as AppInicioRouteImport } from './routes/_app.inicio'
import { Route as AppDeudoresIndexRouteImport } from './routes/_app.deudores.index'
import { Route as AppDeudoresClienteIdRouteImport } from './routes/_app.deudores.$clienteId'

const PinRoute = PinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRegistroRoute = AppRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => AppRoute,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRoute,
} as any)
const AppDeudoresIndexRoute = AppDeudoresIndexRouteImport.update({
  id: '/deudores/',
  path: '/deudores/',
  getParentRoute: () => AppRoute,
} as any)
const AppDeudoresClienteIdRoute = AppDeudoresClienteIdRouteImport.update({
  id: '/deudores/$clienteId',
  path: '/deudores/$clienteId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pin': typeof PinRoute
  '/inicio': typeof AppInicioRoute
  '/registro': typeof AppRegistroRoute
  '/deudores/$clienteId': typeof AppDeudoresClienteIdRoute
  '/deudores/': typeof AppDeudoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pin': typeof PinRoute
  '/inicio': typeof AppInicioRoute
  '/registro': typeof AppRegistroRoute
  '/deudores/$clienteId': typeof AppDeudoresClienteIdRoute
  '/deudores': typeof AppDeudoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pin': typeof PinRoute
  '/_app/inicio': typeof AppInicioRoute
  '/_app/registro': typeof AppRegistroRoute
  '/_app/deudores/$clienteId': typeof AppDeudoresClienteIdRoute
  '/_app/deudores/': typeof AppDeudoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pin'
    | '/inicio'
    | '/registro'
    | '/deudores/$clienteId'
    | '/deudores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pin'
    | '/inicio'
    | '/registro'
    | '/deudores/$clienteId'
    | '/deudores'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/pin'
    | '/_app/inicio'
    | '/_app/registro'
    | '/_app/deudores/$clienteId'
    | '/_app/deudores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PinRoute: typeof PinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pin': {
      id: '/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/registro': {
      id: '/_app/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof AppRegistroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inicio': {
      id: '/_app/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deudores/': {
      id: '/_app/deudores/'
      path: '/deudores'
      fullPath: '/deudores/'
      preLoaderRoute: typeof AppDeudoresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deudores/$clienteId': {
      id: '/_app/deudores/$clienteId'
      path: '/deudores/$clienteId'
      fullPath: '/deudores/$clienteId'
      preLoaderRoute: typeof AppDeudoresClienteIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInicioRoute: typeof AppInicioRoute
  AppRegistroRoute: typeof AppRegistroRoute
  AppDeudoresClienteIdRoute: typeof AppDeudoresClienteIdRoute
  AppDeudoresIndexRoute: typeof AppDeudoresIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInicioRoute: AppInicioRoute,
  AppRegistroRoute: AppRegistroRoute,
  AppDeudoresClienteIdRoute: AppDeudoresClienteIdRoute,
  AppDeudoresIndexRoute: AppDeudoresIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PinRoute: PinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
